<?php


class CCA_Con_CPT extends CCA_CPT_With_Custom_fields {

	public function add_metaboxes() {
		// add con link to competitions
		$cons = get_posts( array( 'post_type' => COSTUME_CON_ARCHIVES_CON_CPT, 'posts_per_page'=>-1));
		$options = array( '' => '');
		foreach ( $cons as $con ) {
			$options[$con->ID] = $con->post_title;
		}
		$cmb = new_cmb2_box( array(
				'id'               => 'con_info_metabox',
				'title'            => __( 'Con Information', 'cmb2' ),
				'object_types'     => array( COSTUME_CON_ARCHIVES_CON_CPT ), // Post type
				'context'          => 'normal',
				'priority'         => 'high',
				'show_names'       => true, // Show field names on the left
			) );

		$albums = get_posts( array( 'post_type' => 'foogallery-album', 'posts_per_page'=>-1));
		$album_list = array( ''=>'');
		foreach ( $albums as $album ) {
			$album_list[ $album->ID] = $album->post_title;
		}
		$cmb->add_field( array(
			'id'    =>  'con_album',
			'name'  =>  'Photo Album',
			'type'  =>  'select',
			'options'   => $album_list,
		));

		parent::add_metaboxes(); // TODO: Change the autogenerated stub
	}

	public function get_competitions( $id ) {
		return get_posts( array(
			'post_type'      => COSTUME_CON_ARCHIVES_COMPETITION_CPT,
			'post_status'    => 'publish',
			'posts_per_page' => - 1,
			'meta_query'     => array(
				array(
					'key'   => 'competition_parent',
					'value' => $id
				)
			)
		) );
	}
}
