<?php

/**
 * The admin-specific functionality of the plugin.
 *
 * @link       http://www.mooberrydreams.com
 * @since      1.0.0
 *
 * @package    Costume_Con_Archives
 * @subpackage Costume_Con_Archives/admin
 */

/**
 * The admin-specific functionality of the plugin.
 *
 * Defines the plugin name, version, and two examples hooks for how to
 * enqueue the admin-specific stylesheet and JavaScript.
 *
 * @package    Costume_Con_Archives
 * @subpackage Costume_Con_Archives/admin
 * @author     Christie <Speich>
 */
class Costume_Con_Archives_Admin {

	/**
	 * The ID of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string $plugin_name The ID of this plugin.
	 */
	private $plugin_name;

	/**
	 * The version of this plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 * @var      string $version The current version of this plugin.
	 */
	private $version;



	/**
	 * Initialize the class and set its properties.
	 *
	 * @param string $plugin_name The name of this plugin.
	 * @param string $version     The version of this plugin.
	 *
	 * @since    1.0.0
	 */
	public function __construct( $plugin_name, $version ) {

		$this->plugin_name = $plugin_name;
		$this->version     = $version;


	}

	/**
	 * Register the stylesheets for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_styles() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Costume_Con_Archives_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Costume_Con_Archives_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_style( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'css/costume-con-archives-admin.css', array(), $this->version, 'all' );

	}

	/**
	 * Register the JavaScript for the admin area.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {

		/**
		 * This function is provided for demonstration purposes only.
		 *
		 * An instance of this class should be passed to the run() function
		 * defined in Costume_Con_Archives_Loader as all of the hooks are defined
		 * in that particular class.
		 *
		 * The Costume_Con_Archives_Loader will then create the relationship
		 * between the defined hooks and the functions defined in this
		 * class.
		 */

		wp_enqueue_script( $this->plugin_name, plugin_dir_url( __FILE__ ) . 'js/costume-con-archives-admin.js', array( 'jquery' ), $this->version, false );
		wp_localize_script( $this->plugin_name,
				'cca_ajax_admin', array(
					'ajax_url'   => admin_url( 'admin-ajax.php' ),
					'ajax_nonce' => wp_create_nonce( 'ajax-admin-nonce' ),
				)
			);

	}


	/**
	 * Hook in and register a metabox to handle a theme options page and adds a menu item.
	 */
	public function register_settings_metabox() {

		$main_settings_page       = new CCA_Main_Settings_Page();
		$tax_Settings_pages       = new CCA_Taxonomy_Settings_Page();
		$con_fields_settings_page = new CCA_Con_Fields_Settings_Page();
		$competition_fields_settings_page = new CCA_Competition_Fields_Settings_Page();
		$photo_fields_settings_page = new CCA_Photo_Fields_Settings_Page();


		$taxonomies = CCA_Taxonomies_Settings::get_taxonomies();
		foreach ( $taxonomies as $taxonomy ) {
			$tax_fields_page = new CCA_Tax_Fields_Settings_Page( $taxonomy );

		}

	}

	/**
	 * Display any admin notices that are available
	 *
	 * @since    1.0.0
	 */
	public function admin_notices() {
		Costume_Con_Archives_Admin_Notice_Manager::display_notices();
	}


	function admin_menu() {
		/**
		 * MIGRATING DATA
		 */
		if ( CCA_Main_Settings::get_show_migration_menu() ) {
			add_submenu_page( 'cca_main_settings', 'Migrate Data', 'Migrate Data', 'manage_options', 'cca-migrate-data', array(
				$this,
				'migrate_data_page'
			) );
		}

	}

	public function migrate_data_page() {
		include 'partials/migrate-data-page.php';

	}

	// render unique id
	public function render_unique_id( $field_args, $escaped_value, $object_id, $object_type, $field_type_object ) {
		echo $field_type_object->input( array(
			'class'    => 'cmb2_unique_id',
			'disabled' => 'true',
			'size'     => 50,
			'desc'  =>  '<p class="cmb2-metabox-description">Autogenerated unique id used to reference this field in the database</p>'
		) );
	}

	// sanitize the field
	public function sanitize_unique_id( $override, $new, $object_id ) {
		// Set unique id if it's not already set
		if ( empty( $new ) ) {
			$value = uniqid( $object_id . '_', false );
		} else {
			$value = $new;
		}

		return $value;
	}

	// render numbers
	public function render_text_number( $field, $escaped_value, $object_id, $object_type, $field_type_object ) {
		echo $field_type_object->input( array( 'class' => 'cmb2-text-small', 'type' => 'number' ) );
	}

	// sanitize the field
	public function sanitize_text_number( $null, $new ) {
		$new = preg_replace( "/[^0-9]/", "", $new );

		return $new;
	}

	/*public function con_cpt_add_metaboxes() {
		$this->con_cpt->add_metaboxes();


		$this->competition_cpt->add_metaboxes();

		$this->photos_cpt->add_metaboxes();*/

		/*$taxonomies = CCA_Taxonomies_Settings::get_taxonomies();
		foreach ( $taxonomies as $taxonomy ) {

			$cmb = new_cmb2_box( array(
				'id'               => $taxonomy->get_name() . '_term_custom_fields',
				'title'            => __( 'Custom Fields', 'cmb2' ),
				'object_types'     => array( 'attachment' ), // Post type
				'taxonomies'       => array( $taxonomy->get_name() ),
				'context'          => 'advanced',
				'priority'         => 'high',
				'show_names'       => true, // Show field names on the left

			) );

			$cmb->add_field( array(
				'id'       => 'test_' . $taxonomy->get_name(),
				'name'     => $taxonomy->get_plural(),
				'type'     => 'taxonomy_select',
				'taxonomy' => $taxonomy->get_name()

			) );
		}*/
	//}


	public function tax_term_metaboxes() {
		$taxonomies = CCA_Taxonomies_Settings::get_taxonomies();
		foreach ( $taxonomies as $taxonomy ) {

			$cmb = new_cmb2_box( array(
				'id'               => $taxonomy->get_name() . '_term_custom_fields',
				'title'            => __( 'Custom Fields', 'cmb2' ),
				'object_types'     => array( 'term' ), // Post type
				'taxonomies'       => array( $taxonomy->get_name() ),
				'context'          => 'normal',
				'priority'         => 'high',
				'show_names'       => true, // Show field names on the left
				'new_term_section' => true,
			) );

			$fields = CCA_Tax_Fields_Settings::get_fields_for_taxonomy( $taxonomy->get_name() );
			foreach ( $fields as $field ) {

				$args = array(
					'name' => $field->name,
					'id'   => $field->id,
				);

				$args['type'] = $field->type;

				if ( $field->has_options() ) {
					$args['options'] = $field->options;
				}

				// if it's a self-referencing taxonomy, remove the current term to avoid circular reference
				if ( $field->is_tax_field ) {
					if ( $field->taxonomy == $taxonomy->get_name() ) {
						unset( $args['options'][ intval( $cmb->object_id ) ] );
					}
				}

				$cmb->add_field( $args );
			}
		}
	}

	public function tax_save_terms( $term_id, $taxonomy ) {

		// for tax term fields that are cross reference fields, we need
		// to save all the terms selected for this term on the other
		//  terms so they stay in sync
		$fields = CCA_Tax_Fields_Settings::get_fields_for_taxonomy( $taxonomy );
		foreach ( $fields as $field ) {
			// this only applies to tax fields that are the same taxonomy
			if ( $field->is_tax_field && $field->taxonomy == $taxonomy ) {

				// get all of the terms selected in this cross reference field
				$terms = get_term_meta( $term_id, $field->id, true );  // returns array of strings that are term_ids
				$terms = array_map( 'intval', $terms ); // convert to ints

				// add in the term we're updating since that wasn't in the list
				$new_terms = $terms;
				$new_terms[] = $term_id;

				foreach ( $terms as $term ) {
					update_term_meta( $term, $field->id, $new_terms );
				}

			}
		}


	}

	public function remove_taxonomy_metaboxes_on_con() {
		$taxonomies = CCA_Taxonomies_Settings::get_taxonomies();
		foreach ( $taxonomies as $taxonomy ) {
			remove_meta_box( 'tagsdiv-' . $taxonomy->get_name(), COSTUME_CON_ARCHIVES_CON_CPT, 'advanced' );
		}
	}

	public function migrate_create_custom_fields() {
		check_ajax_referer( 'ajax-admin-nonce', 'security' );

		$delete = ( isset( $_POST['delete'] ) && $_POST['delete'] == 'true' );
		$types  = isset( $_POST['types'] ) ? $_POST['types'] : array();

		$migration = new CCA_G2_Migration();
		$migration->create_custom_fields( $delete, $types );

		echo 'Done!';
		wp_die();
	}

	public function import_g2_data() {
		check_ajax_referer( 'ajax-admin-nonce', 'security' );

		$delete = ( isset( $_POST['delete'] ) && $_POST['delete'] == 'true' );

		$migration = new CCA_G2_Migration();
		$migration->import_data( $delete );

		echo 'Done!';
		wp_die();
	}

	public function import_g2_photos() {
		check_ajax_referer( 'ajax-admin-nonce', 'security' );

		$delete = ( isset( $_POST['delete'] ) && $_POST['delete'] == 'true' );
		$start =  isset( $_POST['start'] ) ? intval( $_POST['start']) : 0;
		$count =  isset( $_POST['count'] ) ? intval( $_POST['count']) : 100;


		$migration = new CCA_G2_Migration();
		$migration->import_photos( $delete , $start, $count );

		//echo 'Queued!';
		echo $start;
		wp_die();

	}

}
